dist: xenial
language: go

go:
  - "1.10.x"

env:
  global:
    - DEPS_DIR=$HOME/dependencies
  matrix:
    - WITH_TA_LIBRARY=yes
      CGO_CFLAGS=-I$DEPS_DIR/include
      LD_LIBRARY_PATH=$DEPS_DIR/lib
      CGO_LDFLAGS=-L$DEPS_DIR/lib -lta_lib

install:
  - if [ $WITH_TA_LIBRARY = "yes" ]; then
      ./build_talib_from_source.bash $DEPS_DIR;
    fi
  - go get github.com/kjx98/go-talib

script:
    - go test -v ./...
